# Django异常

DJango会抛出一些它自己的异常，以及Python的标准异常。



## Django核心异常

Django核心异常类定义在`django.core.exceptions`中。



### `AppRegistryNotReady`

- *例外* `AppRegistryNotReady`[[source\]](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/_modules/django/core/exceptions.html#AppRegistryNotReady)

  当在[app loading process](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/applications.html#app-loading-process)（初始化ORM）之前尝试使用模型时，会引发此异常。



### `ObjectDoesNotExist`

- *例外* `ObjectDoesNotExist`[[source\]](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/_modules/django/core/exceptions.html#ObjectDoesNotExist)

  The base class for [`DoesNotExist`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/models/instances.html#django.db.models.Model.DoesNotExist) exceptions; a `try/except` for `ObjectDoesNotExist` will catch [`DoesNotExist`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/models/instances.html#django.db.models.Model.DoesNotExist) exceptions for all models.[`ObjectDoesNotExist`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/exceptions.html#django.core.exceptions.ObjectDoesNotExist) 和 [`DoesNotExist`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/models/instances.html#django.db.models.Model.DoesNotExist)的更多信息请见 [`get()`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/models/querysets.html#django.db.models.query.QuerySet.get)。



### `EmptyResultSet`

- *例外* `EmptyResultSet`[[source\]](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/_modules/django/core/exceptions.html#EmptyResultSet)

  如果查询不返回任何结果，则在查询生成期间可能会引发`EmptyResultSet`。 大多数Django项目不会遇到此异常，但它可能有助于实现自定义查找和表达式。**在Django更改1.11：**在旧版本中，它只能从`django.db.models.sql`导入。



### `FieldDoesNotExist`

- *例外* `FieldDoesNotExist`[[source\]](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/_modules/django/core/exceptions.html#FieldDoesNotExist)

  当被请求的字段在模型或模型的父类中不存在时，`FieldDoesNotExist`异常由模型的 `_meta.get_field()`方法抛出。



### `MultipleObjectsReturned`

- *例外* `MultipleObjectsReturned`[[source\]](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/_modules/django/core/exceptions.html#MultipleObjectsReturned)

  [`MultipleObjectsReturned`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/exceptions.html#django.core.exceptions.MultipleObjectsReturned)异常由查询产生，当预期只有一个对象，但是有多个对象返回的时候。 [`django.core.exceptions`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/exceptions.html#module-django.core.exceptions)中提供了此异常的基本版本；每个模型类都包含一个子类的版本，可用于标识已返回多个对象的特定对象类型。详见[`get()`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/models/querysets.html#django.db.models.query.QuerySet.get)。



### `SuspiciousOperation`

- *例外* `SuspiciousOperation`[[source\]](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/_modules/django/core/exceptions.html#SuspiciousOperation)

  当用户进行的操作在安全方面可疑的时候，抛出[`SuspiciousOperation`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/exceptions.html#django.core.exceptions.SuspiciousOperation)异常，例如篡改会话cookie。 `SuspiciousOperation`的子类包括：`DisallowedHost``DisallowedModelAdminLookup``DisallowedModelAdminToField``DisallowedRedirect``InvalidSessionKey``RequestDataTooBig``SuspiciousFileOperation``SuspiciousMultipartForm``SuspiciousSession``TooManyFieldsSent`如果`SuspiciousOperation`异常到达了WSGI处理器层，它会在`Error`层记录，并导致[`HttpResponseBadRequest`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/request-response.html#django.http.HttpResponseBadRequest)异常。 详见[logging documentation](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/topics/logging.html)。



### `PermissionDenied`

- *例外* `PermissionDenied`[[source\]](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/_modules/django/core/exceptions.html#PermissionDenied)

  [`PermissionDenied`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/exceptions.html#django.core.exceptions.PermissionDenied)异常当用户不被允许来执行请求的操作时产生。



### `ViewDoesNotExist`

- *例外* `ViewDoesNotExist`[[source\]](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/_modules/django/core/exceptions.html#ViewDoesNotExist)

  当请求的视图不存在时，[`ViewDoesNotExist`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/exceptions.html#django.core.exceptions.ViewDoesNotExist)异常由[`django.urls`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/urlresolvers.html#module-django.urls)引发。



### `MiddlewareNotUsed`

- *例外* `MiddlewareNotUsed`[[source\]](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/_modules/django/core/exceptions.html#MiddlewareNotUsed)

  当中间件没有在服务器配置中出现时，产生[`MiddlewareNotUsed`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/exceptions.html#django.core.exceptions.MiddlewareNotUsed)异常。



### `ImproperlyConfigured`

- *例外* `ImproperlyConfigured`[[source\]](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/_modules/django/core/exceptions.html#ImproperlyConfigured)

  DJango配置不当时产生[`ImproperlyConfigured`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/exceptions.html#django.core.exceptions.ImproperlyConfigured)异常 -- 例如，`settings.py`中的值不正确或者不可解析。



### `FieldError`

- *例外* `FieldError`[[source\]](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/_modules/django/core/exceptions.html#FieldError)

  [`FieldError`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/exceptions.html#django.core.exceptions.FieldError)异常当模型字段上出现问题时产生。 它会由以下原因造成：模型中的字段与抽象基类中相同名称的字段冲突。排序造成了一个死循环。关键词不能由过滤器参数解析。字段不能由查询参数中的关键词决定。连接（join）不能在指定对象上使用。字段名称不可用。查询包含了无效的 order_by参数。



### `ValidationError`

- *例外* `ValidationError`[[source\]](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/_modules/django/core/exceptions.html#ValidationError)

  当表单或模型字段验证失败时抛出[`ValidationError`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/exceptions.html#django.core.exceptions.ValidationError)异常。 关于验证的更多信息，请见[Form and Field Validation](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/forms/validation.html), [Model Field Validation](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/models/instances.html#validating-objects) 和 [Validator Reference](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/validators.html)。



#### `NON_FIELD_ERRORS`

- `NON_FIELD_ERRORS T0> `

  

在表单或者模型中不属于特定字段的`ValidationError` 被归类为`NON_FIELD_ERRORS`。 此常量用作字典中的键，否则将字段映射到其各自的错误列表。



## URL解析器异常

URL解析器异常在`django.urls`中定义。

**自1.10版以来已弃用** 在旧版本中，这些异常位于`django.core.urlresolvers`中。 从旧位置导入将继续工作，直到Django 2.0。



### `Resolver404`

- *例外* `Resolver404`[[source\]](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/_modules/django/urls/exceptions.html#Resolver404)

  The [`Resolver404`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/exceptions.html#django.urls.Resolver404) exception is raised by [`resolve()`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/urlresolvers.html#django.urls.resolve) if the path passed to `resolve()` doesn’t map to a view. 它是 [`django.http.Http404`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/topics/http/views.html#django.http.Http404)的子类。



### `NoReverseMatch`

- *例外* `NoReverseMatch`[[source\]](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/_modules/django/urls/exceptions.html#NoReverseMatch)

  当您的URLconf中的匹配URL无法根据提供的参数进行标识时，[`NoReverseMatch`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/exceptions.html#django.urls.NoReverseMatch)异常将由[`django.urls`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/urlresolvers.html#module-django.urls)引发。



## 数据库异常

数据库异常由`django.db`导入。

Django封装了标准的数据库异常，以便确保你的DJango代码拥有这些类的通用实现。

- *例外* `Error`[[source\]](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/_modules/django/db/utils.html#Error)

  

- *例外* `InterfaceError`[[source\]](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/_modules/django/db/utils.html#InterfaceError)

  

- *例外* `DatabaseError`[[source\]](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/_modules/django/db/utils.html#DatabaseError)

  

- *例外* `DataError`[[source\]](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/_modules/django/db/utils.html#DataError)

  

- *例外* `OperationalError`[[source\]](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/_modules/django/db/utils.html#OperationalError)

  

- *例外* `IntegrityError`[[source\]](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/_modules/django/db/utils.html#IntegrityError)

  

- *例外* `InternalError`[[source\]](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/_modules/django/db/utils.html#InternalError)

  

- *例外* `ProgrammingError`[[source\]](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/_modules/django/db/utils.html#ProgrammingError)

  

- *例外* `NotSupportedError`[[source\]](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/_modules/django/db/utils.html#NotSupportedError)

  

Django数据库异常的包装器的行为和底层的数据库异常一样。 详见[**PEP 249**](https://www.python.org/dev/peps/pep-0249)，Python 数据库 API 说明 v2.0。

按照 [**PEP 3134**](https://www.python.org/dev/peps/pep-3134)，`__cause__`属性会在原生（底层）的数据库异常中设置，允许访问所提供的任何附加信息。 （请注意，这个属性可以在Python 2和Python 3两者下使用，尽管 [**PEP 3134**](https://www.python.org/dev/peps/pep-3134)通常仅适用于Python 3。 为了避免与Python 3出现意想不到的差异，Django还将确保通过`__cause__`可用的异常具有可用的`__traceback__`属性。

**在Django更改1.10：**

添加了上述的`__traceback__`属性。

- *例外* `楷模。`` ProtectedError T0> `

  

使用[`django.db.models.PROTECT`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/models/fields.html#django.db.models.PROTECT)时，抛出异常来阻止所引用对象的删除。 [`models.ProtectedError`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/exceptions.html#django.db.models.ProtectedError)是[`IntegrityError`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/exceptions.html#django.db.IntegrityError)的子类。



## Http异常

HTTP异常由`django.http`导入。



### `UnreadablePostError`

- *例外* `UnreadablePostError`[[source\]](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/_modules/django/http/request.html#UnreadablePostError)

  用户取消上传时抛出[`UnreadablePostError`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/exceptions.html#django.http.UnreadablePostError)异常。



## 交易异常

事务异常定义在`django.db.transaction`中。



### `TransactionManagementError`

- *例外* `TransactionManagementError`[[source\]](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/_modules/django/db/transaction.html#TransactionManagementError)

  对于数据库事务相关的任何问题，抛出[`TransactionManagementError`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/exceptions.html#django.db.transaction.TransactionManagementError)异常。



## 测试框架异常

由DJango `django.test` 包提供的异常。



### `RedirectCycleError`

- *例外* `客户。`` RedirectCycleError T0> `

  当测试客户端检测到重定向的循环或者过长的链时，抛出[`RedirectCycleError`](https://yiyibooks.cn/__trs__/xx/Django_1.11.6/ref/exceptions.html#django.test.client.RedirectCycleError)异常。



## Python异常

Django在适当的时候也会抛出Python的内建异常。 进一步的信息请见[Built-in Exceptions](https://docs.python.org/3/library/exceptions.html#bltin-exceptions)的Python文档。